name: Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      date_tag: ${{ steps.date.outputs.date_tag }}

    steps:
      - name: Generate date tag
        id: date
        run: echo "date_tag=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            ghcr.io/${{ github.actor }}/learnx:latest
            ghcr.io/${{ github.actor }}/learnx:${{ steps.date.outputs.date_tag }}

      - name: Slim Image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_INCLUDE_PATH: /usr/share/nginx/html
        with:
          target: ghcr.io/${{ github.actor }}/learnx:latest
          tag: |
            slim
            ${{ steps.date.outputs.date_tag }}-slim

      - name: Push to Registry
        run: docker push "ghcr.io/${{ github.actor }}/learnx" --all-tags
